dist: bionic
langauge: python

jobs:
  include:
    - python: '3.6'
    - python: '3.7'

git:
  depth: 1

addons:
  apt:
    packages:
      - cmake
      - python3
      - python3-pip
      - python3-setuptools

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - ./tests/ext

before_install:
  - pip install  --upgrade pip
  - pip install --upgrade setuptools
  - pip install pytest
  - git submodule update --init
  - git lfs pull
  - pip install --upgrade numpy cython
  - pip install -r requirements.txt
  - cmake --version

install:
  - python3 setup.py install

before_script:
  - cd tests

script:
  - pytest ./data/
  - pytest ./util/
  - pytest ./algo/test_base.py
  - pytest ./algo/test_als.py
  - pytest ./algo/test_bpr.py
  - pytest ./algo/test_cfr.py
  - pytest ./algo/test_optimize.py
  - pytest ./algo/test_quickselect.py
  - pytest ./parallel/

notifications:
  email: false
