dist: bionic
sudo: required

langauge: python
python:
  - "3.6"
  - "3.7"

git:
  depth: 1

addons:
  apt:
    packages:
      - cmake
      - python3
      - python3-pip
      - python3-setuptools

cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - ./tests/ext

matrix:
  include:
    - python: 3.7
      before_install:
        - pip3 install --upgrade pip --user
        - pip3 install -r requirements.txt --user
        - pip3 install --upgrade setuptools --user
        - git submodule update --init
        - git lfs pull
        - pip3 install numpy cython --user
        - pip3 install n2 --user
        - cmake --version
        - sudo python3 setup.py install
        - pip3 install pytest --user

before_script:
  - cd tests

script:
  - pytest ./data/
  - pytest ./util/
  - pytest ./algo/test_base.py
  - pytest ./algo/test_als.py
  - pytest ./algo/test_bpr.py
  - pytest ./algo/test_cfr.py
  - pytest ./algo/test_optimize.py
  - pytest ./algo/test_quickselect.py
  - pytest ./parallel/

notifications:
  email: false

virtualenv:
  system_site_packages: true
